import './globals.css'
import {Lato} from 'next/font/google'
import {NextFont} from "next/dist/compiled/@next/font";
import "./utils/helpers/reset.scss";
import {ToastContainer} from "react-toastify";
import "react-toastify/dist/ReactToastify.css"


const lato: NextFont = Lato({
    subsets: ['latin'],
    weight: "400",
})




export const metadata = {
    icons: {
        icon: '/favicon.ico',
    },
    title: 'Portfolio',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <>
            <html lang="en">
            <body className={lato.className}>
            <div>
                {children}

                <ToastContainer
                position="bottom-right"
                hideProgressBar={false}
                closeOnClick
                rtl={false}
                theme="light"
                ></ToastContainer>
            </div>
            </body>
            </html>
        </>

    )
}
