import './globals.css'
import {Lato} from 'next/font/google'
import {NextFont} from "next/dist/compiled/@next/font";

const lato:NextFont = Lato({
    subsets: ['latin'],
    weight: "400",
})



export const metadata = {
    title: 'portfolio-app',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={lato.className}>
        {children}
        </body>
        </html>
    )
}
